# Generated by Django 3.2.10 on 2022-01-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='collects',
            field=models.ManyToManyField(blank=True, to='app01.Articles', verbose_name='收藏的文章'),
        ),
    ]
