# Generated by Django 3.2.10 on 2022-01-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20220118_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='文章链接'),
        ),
    ]
