# Generated by Django 3.2.10 on 2022-02-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20220210_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='token',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sign_status',
            field=models.IntegerField(choices=[(0, '用户名注册'), (1, 'QQ注册'), (2, '手机号注册'), (3, '邮箱注册')], default=0, verbose_name='注册方式'),
        ),
    ]
