# Generated by Django 3.2.10 on 2022-02-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20220213_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='account_status',
            field=models.IntegerField(choices=[(0, '账号正常'), (1, '账号异常'), (2, '账号被封禁')], default=0, verbose_name='账号状态'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='avatar_url',
            field=models.URLField(help_text='可能是其他平台的头像', null=True, verbose_name='用户头像'),
        ),
    ]
