# Generated by Django 3.2.10 on 2022-02-13 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20220213_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='a_unique_id',
            field=models.CharField(blank=True, help_text='其他平台的唯一登录id', max_length=64, null=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.avatars', verbose_name='用户头像'),
        ),
    ]
