# Generated by Django 3.2.10 on 2022-02-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20220223_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodcomment',
            name='addr',
            field=models.JSONField(null=True, verbose_name='用户地址信息'),
        ),
        migrations.AddField(
            model_name='moodcomment',
            name='ip',
            field=models.GenericIPAddressField(default='120.228.2.238', verbose_name='ip地址'),
        ),
    ]
