# Generated by Django 3.2.10 on 2022-03-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20220301_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='navs',
            field=models.ManyToManyField(blank=True, to='app01.Navs', verbose_name='收藏的网站'),
        ),
    ]
