# Generated by Django 3.2.10 on 2022-03-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_userinfo_navs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyInfo',
        ),
    ]
