# Generated by Django 3.2.10 on 2022-03-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_delete_myinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
    ]
