# Generated by Django 3.2.10 on 2022-03-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_delete_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='标题')),
                ('article', models.ManyToManyField(to='app01.Articles', verbose_name='文章')),
            ],
            options={
                'verbose_name_plural': '项目相关',
            },
        ),
    ]
