# Generated by Django 3.2.10 on 2022-03-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='a_unique_id',
            new_name='token',
        ),
    ]
