# Generated by Django 3.2.10 on 2022-03-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_rename_a_unique_id_userinfo_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='login_date',
            field=models.DateTimeField(auto_now=True, verbose_name='登录时间'),
        ),
    ]
