# Generated by Django 3.2.10 on 2022-03-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_userinfo_login_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='login_date',
        ),
    ]
