# Generated by Django 3.2.10 on 2022-03-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_remove_userinfo_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='addr',
            field=models.JSONField(null=True, verbose_name='用户地址信息'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ip',
            field=models.GenericIPAddressField(default='120.228.2.238', verbose_name='ip地址'),
        ),
    ]
